name: testpr
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  
jobs: 
 testingpull:
  name: ubuntu-latest
  runs-on: ubuntu
  
  steps:
   - name: clone the code from repository
     uses: actions/checkout@v3
   - name: dotnet SDK setup
     uses: actions/setup-dotnet@v1
     with:
      dotnet-version: 5.x
   - name: restore
     run: dotnet restore src/WebService/WebService.csproj
   - name: build dotnet
     run: build dotnet src/WebService/WebService.csproj
        
  
